unused_args = false

globals = {
  -- These are from the "enums.lua" file in the "scripts" subdirectory
  "BombVariant",
  "ButtonAction",
  "CacheFlag",
  "Card",
  "Challenge",
  "CoinSubType",
  "CollectibleType",
  "Color",
  "DamageFlag",
  "Direction",
  "DoorSlot",
  "EffectVariant",
  "EntityCollisionClass",
  "EntityFlag",
  "EntityPartition",
  "EntityPtr",
  "EntityRef",
  "EntityType",
  "FamiliarVariant",
  "Game",
  "GetPtrHash",
  "GridCollisionClass",
  "GridEntityType",
  "GridRooms",
  "ItemPoolType",
  "Input",
  "InputHook",
  "Isaac",
  "ItemType",
  "Keyboard",
  "LevelCurse",
  "LevelStage",
  "ModCallbacks",
  "NpcState",
  "PickupVariant",
  "PillColor",
  "PillEffect",
  "PlayerForm",
  "PlayerType",
  "ProjectileFlags",
  "ProjectileParams",
  "ProjectileVariant",
  "Random",
  "RandomVector",
  "RegisterMod",
  "RNG",
  "RoomShape",
  "RoomType",
  "SeedEffect",
  "SFXManager",
  "SoundEffect",
  "Sprite",
  "StageType",
  "TearFlags",
  "TearVariant",
  "TrinketType",
  "Vector",

  -- Racing+ global variables
  "RacingPlusGlobals",
  "RacingPlusSchoolbag",
  "SinglePlayerCoopBabies",

  -- This is used in the True Co-op Mod
  "InfinityTrueCoopInterface",
}
